import { execSync } from "child_process";
import { NextRequest, NextResponse } from "next/server";
import path from "path";
import fs from "fs";
import crypto from "crypto";

const { create: createYoutubeDl } = require("youtube-dl-exec");

// Resolve binary path
const binaryName = process.platform === "win32" ? "yt-dlp.exe" : "yt-dlp_linux";
const absoluteBinaryPath = path.join(process.cwd(), "bin", binaryName);

// Ensure Linux execution permissions
if (process.platform !== "win32" && fs.existsSync(absoluteBinaryPath)) {
  try {
    execSync(`chmod +x "${absoluteBinaryPath}"`);
  } catch (err) {
    console.warn("Permission adjustment warning:", err);
  }
}

const youtubedl = createYoutubeDl(absoluteBinaryPath);

export async function POST(request: NextRequest): Promise<NextResponse> {
  let uniqueCookiePath = "";

  try {
    const { url } = await request.json();

    if (!url) {
      return NextResponse.json({ error: "URL is required" }, { status: 400 });
    }

    // Generate unique file path per invocation to prevent Vercel file collisions
    const fileId = crypto.randomBytes(8).toString("hex");
    uniqueCookiePath = path.join("/tmp", `cookies_${fileId}.txt`);

    if (process.env.YOUTUBE_COOKIES_TXT) {
      const cleanCookies = process.env.YOUTUBE_COOKIES_TXT.replace(
        /\\n/g,
        "\n",
      );
      fs.writeFileSync(uniqueCookiePath, cleanCookies, "utf8");
    }

    const options: Record<string, any> = {
      dumpSingleJson: true,
      skipDownload: true,
      noWarnings: true,
      noCheckCertificates: true,
      forceIpv4: true,

      // Subtitle extraction flags
      writeSubs: true,
      writeAutoSubs: true,
      subLangs: "all",

      // Prevent stale cache errors on serverless
      noCacheDir: true,

      // CRITICAL FIX FOR DATACENTER IPs:
      // Uses client rotation (tv_downgraded + mweb) which bypasses the mandatory PO Token check
      extractorArgs: "youtube:player_client=tv_downgraded,mweb,android_vr",
    };

    // Attach cookies if valid
    if (
      fs.existsSync(uniqueCookiePath) &&
      fs.statSync(uniqueCookiePath).size > 0
    ) {
      options.cookies = uniqueCookiePath;
    }

    // Execute yt-dlp
    const info = await youtubedl(url, options);

    // Clean up temporary cookie file
    if (fs.existsSync(uniqueCookiePath)) {
      fs.unlinkSync(uniqueCookiePath);
    }

    // Extract subtitles dictionary
    const manualSubs = info.subtitles || {};
    const autoSubs = info.automatic_captions || {};

    return NextResponse.json({
      videoId: info.id,
      title: info.title,
      duration: info.duration,
      subtitles: {
        manual: manualSubs,
        autoGenerated: autoSubs,
      },
    });
  } catch (error) {
    // Cleanup cookie file on failure
    if (uniqueCookiePath && fs.existsSync(uniqueCookiePath)) {
      try {
        fs.unlinkSync(uniqueCookiePath);
      } catch {}
    }

    console.error("yt-dlp Extraction Error:", error);
    return NextResponse.json(
      {
        error: "yt-dlp extraction failed",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}
