// app/api/subtitles/route.ts

import { NextRequest, NextResponse } from "next/server";

interface SubtitleFormat {
  ext: string;
  url: string;
}

interface ProcessedSubtitleTrack {
  languageCode: string;
  languageName?: string;
  vttUrl?: string;
  isAutoGenerated: boolean;
  allFormats: SubtitleFormat[];
}

const SUPPORTED_FORMATS = ["srt", "vtt", "txt", "json"];

function buildFormatsList(langCode: string, videoId: string): SubtitleFormat[] {
  return SUPPORTED_FORMATS.map((ext) => ({
    ext,
    url: `/api/subtitles/download?videoId=${videoId}&langCode=${langCode}&ext=${ext}`,
  }));
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { videoId } = body;

    if (!videoId) {
      return NextResponse.json(
        { error: "Video ID is required" },
        { status: 400 },
      );
    }

    // 1. Fetch watch page HTML with desktop browser headers
    const response = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9",
        Cookie: "CONSENT=YES+cb; SOCS=CAI;",
      },
    });

    if (!response.ok) {
      return NextResponse.json(
        { error: "Failed to fetch video page" },
        { status: 500 },
      );
    }

    const html = await response.text();

    // 2. Extract ytInitialPlayerResponse JSON payload
    // Note: Replaced /s flag with [\s\S] to maintain ES5/ES6 compatibility
    let playerResponse: any = null;

    // Pattern A: standard var ytInitialPlayerResponse = {...};
    const matchA = html.match(/ytInitialPlayerResponse\s*=\s*({[\s\S]+?});/);
    if (matchA) {
      try {
        playerResponse = JSON.parse(matchA[1]);
      } catch (e) {
        /* parse fallback */
      }
    }

    // Pattern B: window["ytInitialPlayerResponse"] = {...};
    if (!playerResponse) {
      const matchB = html.match(
        /window\["ytInitialPlayerResponse"\]\s*=\s*({[\s\S]+?});/,
      );
      if (matchB) {
        try {
          playerResponse = JSON.parse(matchB[1]);
        } catch (e) {
          /* parse fallback */
        }
      }
    }

    let title = "YouTube Video";
    let duration = 0;
    let captionTracks: any[] = [];

    if (playerResponse) {
      title = playerResponse?.videoDetails?.title || title;
      duration = parseInt(
        playerResponse?.videoDetails?.lengthSeconds || "0",
        10,
      );
      captionTracks =
        playerResponse?.captions?.playerCaptionsTracklistRenderer
          ?.captionTracks || [];
    }

    // 3. Process extracted caption tracks
    const manualTracks: ProcessedSubtitleTrack[] = [];
    const autoTracks: ProcessedSubtitleTrack[] = [];
    const seenLanguages = new Set<string>();

    for (const track of captionTracks) {
      const languageCode = track.languageCode;
      const languageName =
        track.name?.simpleText ||
        track.name?.runs?.[0]?.text ||
        languageCode.toUpperCase();

      const isAuto =
        track.kind === "asr" ||
        (track.vssId && track.vssId.startsWith("a.")) ||
        false;

      const trackKey = `${languageCode}_${isAuto ? "auto" : "manual"}`;
      if (seenLanguages.has(trackKey)) continue;
      seenLanguages.add(trackKey);

      const processedTrack: ProcessedSubtitleTrack = {
        languageCode,
        languageName,
        vttUrl: track.baseUrl,
        isAutoGenerated: isAuto,
        allFormats: buildFormatsList(languageCode, videoId),
      };

      if (isAuto) {
        autoTracks.push(processedTrack);
      } else {
        manualTracks.push(processedTrack);
      }
    }

    // 4. Fallback: If page didn't contain captionTracks directly, query timedtext with language parameters
    if (manualTracks.length === 0 && autoTracks.length === 0) {
      const languagesToTest = [
        "en",
        "es",
        "fr",
        "de",
        "pt",
        "it",
        "hi",
        "ja",
        "ko",
        "zh",
      ];

      for (const lang of languagesToTest) {
        const checkRes = await fetch(
          `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${lang}`,
        );
        if (checkRes.ok) {
          const text = await checkRes.text();
          if (text && text.length > 100) {
            manualTracks.push({
              languageCode: lang,
              languageName: lang.toUpperCase(),
              isAutoGenerated: false,
              allFormats: buildFormatsList(lang, videoId),
            });
          }
        }
      }
    }

    return NextResponse.json({
      videoId,
      title,
      duration,
      subtitles: {
        manual: manualTracks,
        autoGenerated: autoTracks,
      },
    });
  } catch (error: any) {
    console.error("Error in /api/subtitles:", error);
    return NextResponse.json(
      { error: error.message || "Failed to process subtitles request" },
      { status: 500 },
    );
  }
}
