// app/api/subtitles/route.ts

import { NextRequest, NextResponse } from "next/server";

interface SubtitleFormat {
  ext: string;
  url: string;
}

interface ProcessedSubtitleTrack {
  languageCode: string;
  languageName?: string;
  vttUrl?: string;
  isAutoGenerated: boolean;
  allFormats: SubtitleFormat[];
}

const SUPPORTED_FORMATS = ["srt", "vtt", "txt", "json"];

function buildFormatsList(langCode: string, videoId: string): SubtitleFormat[] {
  return SUPPORTED_FORMATS.map((ext) => ({
    ext,
    url: `/api/subtitles/download?videoId=${videoId}&langCode=${langCode}&ext=${ext}`,
  }));
}

function parseCaptionTracks(captionTracks: any[], videoId: string) {
  const manualTracks: ProcessedSubtitleTrack[] = [];
  const autoTracks: ProcessedSubtitleTrack[] = [];
  const seenLanguages = new Set<string>();

  for (const track of captionTracks) {
    const languageCode = track.languageCode;
    const languageName =
      track.name?.simpleText ||
      track.name?.runs?.[0]?.text ||
      languageCode.toUpperCase();

    const isAuto =
      track.kind === "asr" ||
      (track.vssId && track.vssId.startsWith("a.")) ||
      false;

    const trackKey = `${languageCode}_${isAuto ? "auto" : "manual"}`;
    if (seenLanguages.has(trackKey)) continue;
    seenLanguages.add(trackKey);

    const processedTrack: ProcessedSubtitleTrack = {
      languageCode,
      languageName,
      vttUrl: track.baseUrl,
      isAutoGenerated: isAuto,
      allFormats: buildFormatsList(languageCode, videoId),
    };

    if (isAuto) {
      autoTracks.push(processedTrack);
    } else {
      manualTracks.push(processedTrack);
    }
  }

  return { manualTracks, autoTracks };
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { videoId } = body;

    if (!videoId) {
      return NextResponse.json(
        { error: "Video ID is required" },
        { status: 400 },
      );
    }

    let title = "YouTube Video";
    let duration = 0;
    let captionTracks: any[] = [];

    // Attempt 1: Fetch via Embed Page (Bypasses Watch Page Bot Checks on Serverless)
    try {
      const embedRes = await fetch(`https://www.youtube.com/embed/${videoId}`, {
        headers: {
          "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
          "Accept-Language": "en-US,en;q=0.9",
        },
      });

      if (embedRes.ok) {
        const embedHtml = await embedRes.text();
        const playerResponseMatch = embedHtml.match(
          /ytInitialPlayerResponse\s*=\s*({[\s\S]+?});/,
        );

        if (playerResponseMatch) {
          const playerResponse = JSON.parse(playerResponseMatch[1]);
          title = playerResponse?.videoDetails?.title || title;
          duration = parseInt(
            playerResponse?.videoDetails?.lengthSeconds || "0",
            10,
          );
          captionTracks =
            playerResponse?.captions?.playerCaptionsTracklistRenderer
              ?.captionTracks || [];
        }
      }
    } catch (e) {
      console.warn("Embed page fetch failed:", e);
    }

    // Attempt 2: Fallback to Watch Page if Embed returned no captions
    if (captionTracks.length === 0) {
      try {
        const watchRes = await fetch(
          `https://www.youtube.com/watch?v=${videoId}`,
          {
            headers: {
              "User-Agent":
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
              "Accept-Language": "en-US,en;q=0.9",
              Cookie: "CONSENT=YES+cb; SOCS=CAI;",
            },
          },
        );

        if (watchRes.ok) {
          const watchHtml = await watchRes.text();
          const match =
            watchHtml.match(/ytInitialPlayerResponse\s*=\s*({[\s\S]+?});/) ||
            watchHtml.match(
              /window\["ytInitialPlayerResponse"\]\s*=\s*({[\s\S]+?});/,
            );

          if (match) {
            const playerResponse = JSON.parse(match[1]);
            title = playerResponse?.videoDetails?.title || title;
            duration = parseInt(
              playerResponse?.videoDetails?.lengthSeconds || "0",
              10,
            );
            captionTracks =
              playerResponse?.captions?.playerCaptionsTracklistRenderer
                ?.captionTracks || [];
          }
        }
      } catch (e) {
        console.warn("Watch page fetch failed:", e);
      }
    }

    // Attempt 3: InnerTube API with Embedded Web Client context (Serverless safe)
    if (captionTracks.length === 0) {
      try {
        const innertubeRes = await fetch(
          `https://www.youtube.com/youtubei/v1/player?key=AIzaSyAO_FJ2M3f_X6-_f0_q_W910-o3x_w`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "User-Agent":
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
            },
            body: JSON.stringify({
              context: {
                client: {
                  clientName: "WEB_EMBEDDED_PLAYER",
                  clientVersion: "1.20240320.00.00",
                  hl: "en",
                  gl: "US",
                },
              },
              videoId: videoId,
            }),
          },
        );

        if (innertubeRes.ok) {
          const data = await innertubeRes.json();
          title = data?.videoDetails?.title || title;
          duration = parseInt(data?.videoDetails?.lengthSeconds || "0", 10);
          captionTracks =
            data?.captions?.playerCaptionsTracklistRenderer?.captionTracks ||
            [];
        }
      } catch (e) {
        console.warn("InnerTube API fallback failed:", e);
      }
    }

    const { manualTracks, autoTracks } = parseCaptionTracks(
      captionTracks,
      videoId,
    );

    return NextResponse.json({
      videoId,
      title,
      duration,
      subtitles: {
        manual: manualTracks,
        autoGenerated: autoTracks,
      },
    });
  } catch (error: any) {
    console.error("Error in /api/subtitles:", error);
    return NextResponse.json(
      { error: error.message || "Failed to process subtitles request" },
      { status: 500 },
    );
  }
}
