"use client";

import { Field, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { useState, useMemo } from "react";
import { Button } from "@/components/ui/button";
import Image from "next/image";

interface SubtitleFormat {
  ext: string;
  url: string;
}

interface ProcessedSubtitleTrack {
  languageCode: string;
  languageName?: string;
  vttUrl?: string;
  allFormats: SubtitleFormat[];
}

interface ProcessedSubtitlesResponse {
  videoId: string;
  title: string;
  duration: number;
  subtitles: {
    manual: ProcessedSubtitleTrack[];
    autoGenerated: ProcessedSubtitleTrack[];
  };
}

function extractYouTubeVideoId(url: string): string | null {
  if (!url) return null;
  const regex =
    /(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/|youtube\.com\/shorts\/)([^"&?\/\s]{11})/;
  const match = url.trim().match(regex);
  return match ? match[1] : null;
}

function formatDuration(seconds: number): string {
  if (!seconds || seconds <= 0) return "0s";

  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hrs > 0) {
    return `${hrs}h ${mins}m ${secs}s`;
  }

  if (mins > 0) {
    return `${mins}m ${secs}s`;
  }

  return `${secs}s`;
}

export default function Home() {
  const [url, setUrl] = useState("");
  const [urlError, setUrlError] = useState<string | null>(null);
  const [data, setData] = useState<ProcessedSubtitlesResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [downloadingKey, setDownloadingKey] = useState<string | null>(null);

  // Search states for each section
  const [manualSearch, setManualSearch] = useState("");
  const [autoSearch, setAutoSearch] = useState("");

  const handleUrlChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setUrl(value);

    // Clear error when typing
    if (urlError) setUrlError(null);
  };

  const clearUrl = () => {
    setUrl("");
    if (urlError) setUrlError(null);
  };

  const fetchSubtitles = async () => {
    const extractedId = extractYouTubeVideoId(url);

    if (!extractedId) {
      setUrlError("Please enter a valid YouTube video or shorts URL.");
      return;
    }

    setUrlError(null);
    setLoading(true);
    setData(null);
    setManualSearch("");
    setAutoSearch("");

    // Construct clean normalized YouTube URL to send to backend
    const normalizedUrl = `https://www.youtube.com/watch?v=${extractedId}`;

    try {
      const response = await fetch("/api/subtitles", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ url: normalizedUrl, videoId: extractedId }),
      });

      const result = await response.json();
      if (response.ok) {
        setData(result);
      } else {
        setUrlError(result.error || "Failed to fetch subtitles");
      }
    } catch (error) {
      console.error("Failed to fetch subtitles:", error);
      setUrlError("An unexpected error occurred. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  async function handleDownloadSubtitle(
    langCode: string,
    ext: string,
    isAuto: boolean,
  ) {
    if (!data) return;

    const currentKey = `${langCode}_${ext}_${isAuto ? "auto" : "manual"}`;
    setDownloadingKey(currentKey);

    try {
      const response = await fetch("/api/subtitles/download", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          videoUrl: `https://www.youtube.com/watch?v=${data.videoId}`,
          langCode,
          ext,
          isAuto,
          videoTitle: data.title,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        alert(errorData.error || "Download failed");
        return;
      }

      const blob = await response.blob();
      const blobUrl = window.URL.createObjectURL(blob);

      const safeTitle = data.title.replace(/[^a-zA-Z0-9_-]/g, "_");
      const filename = `${safeTitle}_${langCode}.${ext}`;

      const a = document.createElement("a");
      a.href = blobUrl;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();

      window.URL.revokeObjectURL(blobUrl);
    } catch (err) {
      console.error("Error during download:", err);
      alert("An unexpected error occurred while downloading.");
    } finally {
      setDownloadingKey(null);
    }
  }

  // Filtered manual subtitle tracks based on search input
  const filteredManualSubtitles = useMemo(() => {
    if (!data?.subtitles?.manual) return [];
    if (!manualSearch.trim()) return data.subtitles.manual;
    const query = manualSearch.toLowerCase();
    return data.subtitles.manual.filter(
      (track) =>
        track.languageName?.toLowerCase().includes(query) ||
        track.languageCode.toLowerCase().includes(query),
    );
  }, [data, manualSearch]);

  // Filtered auto-generated subtitle tracks based on search input
  const filteredAutoSubtitles = useMemo(() => {
    if (!data?.subtitles?.autoGenerated) return [];
    if (!autoSearch.trim()) return data.subtitles.autoGenerated;
    const query = autoSearch.toLowerCase();
    return data.subtitles.autoGenerated.filter(
      (track) =>
        track.languageName?.toLowerCase().includes(query) ||
        track.languageCode.toLowerCase().includes(query),
    );
  }, [data, autoSearch]);

  return (
    <div className="min-h-screen w-full flex flex-col bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100">
      {/* Top Navbar Header */}
      <header className="w-full border-b border-zinc-200 dark:border-zinc-800 bg-white/80 dark:bg-zinc-900/80 backdrop-blur-md sticky top-0 z-50">
        <div className="w-full px-4 sm:px-8 py-3.5 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Image
              src="/logo.svg"
              alt="YT Subtitles Download Logo"
              width={32}
              height={32}
              priority
            />
            <span className="font-bold text-lg tracking-tight">
              <span className="text-red-600">YTube</span>Subtitles
            </span>
          </div>
          <div className="text-xs text-zinc-500 dark:text-zinc-400 font-medium hidden sm:block">
            {/* YTube Subtitles Download */}
          </div>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 w-full px-4 sm:px-8 py-8 flex flex-col gap-8 max-w-[1600px] mx-auto">
        {/* Search Hero Section */}
        <section className="w-full max-w-3xl mx-auto flex flex-col items-center gap-4 text-center">
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">
              Download Subtitles & Captions
            </h1>
            <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1">
              Extract auto-generated or manual YouTube subtitles in multiple
              formats (.vtt, .srt, .txt, etc.)
            </p>
          </div>

          <div className="w-full flex flex-col gap-1 mt-2">
            <div className="w-full flex flex-col sm:flex-row gap-3 items-end">
              <div className="w-full text-left">
                <Field>
                  <FieldLabel
                    htmlFor="youtube-url"
                    className="text-xs font-semibold text-zinc-600 dark:text-zinc-400"
                  >
                    YouTube Video URL
                  </FieldLabel>
                  <div className="relative w-full">
                    <Input
                      id="youtube-url"
                      type="text"
                      placeholder="https://www.youtube.com/watch?v=... or https://youtu.be/..."
                      value={url}
                      onChange={handleUrlChange}
                      onKeyDown={(e) => e.key === "Enter" && fetchSubtitles()}
                      className={`w-full h-11 pr-10 bg-white dark:bg-zinc-900 border-zinc-300 dark:border-zinc-800 focus:ring-2 focus:ring-red-500 ${
                        urlError
                          ? "border-red-500 dark:border-red-500 focus:ring-red-500"
                          : ""
                      }`}
                    />
                    {url && (
                      <button
                        type="button"
                        onClick={clearUrl}
                        aria-label="Clear input"
                        className="absolute right-3 top-1/2 -translate-y-1/2 p-1 text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200 transition-colors rounded-full focus:outline-none"
                      >
                        <svg
                          className="w-4 h-4"
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M6 18L18 6M6 6l12 12"
                          />
                        </svg>
                      </button>
                    )}
                  </div>
                </Field>
              </div>
              <Button
                onClick={fetchSubtitles}
                disabled={loading || !url.trim()}
                className="w-full sm:w-auto h-11 px-6 bg-red-600 hover:bg-red-700 text-white font-medium transition-all shrink-0 cursor-pointer disabled:cursor-not-allowed"
              >
                {loading ? "Extracting..." : "Fetch Subtitles"}
              </Button>
            </div>

            {/* Validation Error Message */}
            {urlError && (
              <p className="text-xs text-red-500 text-left font-medium mt-1">
                {urlError}
              </p>
            )}
          </div>
        </section>

        {/* Subtitle Downloads Display */}
        {data && (
          <div className="w-full flex flex-col gap-10 mt-2 animate-in fade-in duration-300">
            {/* Video Overview Banner with Interactive Thumbnail */}
            <div className="p-5 border rounded-xl bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-6">
              <div className="flex-1 flex flex-col justify-between">
                <div>
                  <h2 className="text-lg sm:text-xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
                    {data.title}
                  </h2>
                  <div className="flex flex-wrap items-center gap-3 text-xs text-zinc-500 dark:text-zinc-400 mt-2">
                    <span>
                      Duration:{" "}
                      <strong className="text-zinc-700 dark:text-zinc-300">
                        {formatDuration(data.duration)}
                      </strong>
                    </span>
                    <span>•</span>
                    <span>
                      Video ID:{" "}
                      <code className="bg-zinc-100 dark:bg-zinc-800 px-1.5 py-0.5 rounded font-mono">
                        {data.videoId}
                      </code>
                    </span>
                  </div>
                </div>
              </div>

              {/* Clickable Video Thumbnail */}
              <a
                href={`https://www.youtube.com/watch?v=${data.videoId}`}
                target="_blank"
                rel="noopener noreferrer"
                title="Watch on YouTube"
                className="group relative w-full sm:w-52 aspect-video rounded-lg overflow-hidden border border-zinc-200 dark:border-zinc-800 bg-zinc-100 dark:bg-zinc-800 shrink-0 cursor-pointer shadow-sm hover:shadow-md transition-all"
              >
                <img
                  src={`https://img.youtube.com/vi/${data.videoId}/hqdefault.jpg`}
                  alt={data.title}
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                  loading="lazy"
                />
                <div className="absolute inset-0 bg-black/20 group-hover:bg-black/40 transition-colors flex items-center justify-center">
                  <div className="h-10 w-10 rounded-full bg-red-600/90 group-hover:bg-red-600 group-hover:scale-110 transition-all flex items-center justify-center text-white shadow-lg">
                    <svg
                      className="w-5 h-5 fill-current ml-0.5"
                      viewBox="0 0 24 24"
                    >
                      <path d="M8 5v14l11-7z" />
                    </svg>
                  </div>
                </div>
              </a>
            </div>

            {/* Manual Subtitles Section */}
            <section className="flex flex-col gap-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-zinc-200 dark:border-zinc-800">
                <div className="flex items-center gap-3">
                  <h3 className="text-lg font-bold tracking-tight">
                    Manual Subtitles
                  </h3>
                  <span className="text-xs bg-emerald-100 text-emerald-800 dark:bg-emerald-950/80 dark:text-emerald-300 px-2.5 py-0.5 rounded-full font-bold border border-emerald-200 dark:border-emerald-800">
                    {filteredManualSubtitles.length}
                  </span>
                </div>

                {/* Manual Section Search Bar */}
                {data.subtitles?.manual?.length > 0 && (
                  <div className="w-full sm:w-64">
                    <Input
                      type="text"
                      placeholder="Search language or code..."
                      value={manualSearch}
                      onChange={(e) => setManualSearch(e.target.value)}
                      className="h-9 text-xs bg-white dark:bg-zinc-900 border-zinc-300 dark:border-zinc-800"
                    />
                  </div>
                )}
              </div>

              {data.subtitles?.manual?.length === 0 ? (
                <div className="p-6 border rounded-xl bg-white/50 dark:bg-zinc-900/50 text-center text-sm text-zinc-500 italic">
                  No manual subtitles found for this video.
                </div>
              ) : filteredManualSubtitles.length === 0 ? (
                <div className="p-6 border rounded-xl bg-white/50 dark:bg-zinc-900/50 text-center text-sm text-zinc-500">
                  No manual subtitles match &quot;{manualSearch}&quot;.
                </div>
              ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                  {filteredManualSubtitles.map((track) => (
                    <div
                      key={track.languageCode}
                      className="p-4 border rounded-xl bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 flex flex-col justify-between gap-3 shadow-sm hover:border-zinc-300 dark:hover:border-zinc-700 transition-all"
                    >
                      <div className="flex justify-between items-start gap-2">
                        <span className="font-semibold text-sm line-clamp-1">
                          {track.languageName || track.languageCode}
                        </span>
                        <span className="text-xs font-mono text-zinc-500 bg-zinc-100 dark:bg-zinc-800 px-1.5 py-0.5 rounded shrink-0">
                          {track.languageCode}
                        </span>
                      </div>

                      <div className="flex flex-wrap gap-1.5 pt-2 border-t border-zinc-100 dark:border-zinc-800/80">
                        {track.allFormats.map((fmt) => {
                          const key = `${track.languageCode}_${fmt.ext}_manual`;
                          const isDownloading = downloadingKey === key;

                          return (
                            <button
                              key={fmt.ext}
                              onClick={() =>
                                handleDownloadSubtitle(
                                  track.languageCode,
                                  fmt.ext,
                                  false,
                                )
                              }
                              disabled={downloadingKey !== null}
                              className="px-2.5 py-1 text-xs font-mono font-medium rounded-md bg-zinc-100 hover:bg-red-50 hover:text-red-600 dark:bg-zinc-800 dark:hover:bg-red-950/50 dark:hover:text-red-400 border border-zinc-200 dark:border-zinc-700 transition-colors uppercase cursor-pointer disabled:cursor-not-allowed disabled:opacity-50 flex items-center justify-center min-w-[42px]"
                            >
                              {isDownloading ? (
                                <svg
                                  className="animate-spin h-3.5 w-3.5 text-red-600 dark:text-red-400"
                                  xmlns="http://www.w3.org/2000/svg"
                                  fill="none"
                                  viewBox="0 0 24 24"
                                >
                                  <circle
                                    className="opacity-25"
                                    cx="12"
                                    cy="12"
                                    r="10"
                                    stroke="currentColor"
                                    strokeWidth="4"
                                  ></circle>
                                  <path
                                    className="opacity-75"
                                    fill="currentColor"
                                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                                  ></path>
                                </svg>
                              ) : (
                                `.${fmt.ext}`
                              )}
                            </button>
                          );
                        })}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </section>

            {/* Auto-Generated Subtitles Section */}
            <section className="flex flex-col gap-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-zinc-200 dark:border-zinc-800">
                <div className="flex items-center gap-3">
                  <h3 className="text-lg font-bold tracking-tight">
                    Auto-Generated Captions
                  </h3>
                  <span className="text-xs bg-blue-100 text-blue-800 dark:bg-blue-950/80 dark:text-blue-300 px-2.5 py-0.5 rounded-full font-bold border border-blue-200 dark:border-blue-800">
                    {filteredAutoSubtitles.length}
                  </span>
                </div>

                {/* Auto Section Search Bar */}
                {data.subtitles?.autoGenerated?.length > 0 && (
                  <div className="w-full sm:w-64">
                    <Input
                      type="text"
                      placeholder="Search language or code..."
                      value={autoSearch}
                      onChange={(e) => setAutoSearch(e.target.value)}
                      className="h-9 text-xs bg-white dark:bg-zinc-900 border-zinc-300 dark:border-zinc-800"
                    />
                  </div>
                )}
              </div>

              {data.subtitles?.autoGenerated?.length === 0 ? (
                <div className="p-6 border rounded-xl bg-white/50 dark:bg-zinc-900/50 text-center text-sm text-zinc-500 italic">
                  No auto-generated captions found.
                </div>
              ) : filteredAutoSubtitles.length === 0 ? (
                <div className="p-6 border rounded-xl bg-white/50 dark:bg-zinc-900/50 text-center text-sm text-zinc-500">
                  No auto-generated captions match &quot;{autoSearch}&quot;.
                </div>
              ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                  {filteredAutoSubtitles.map((track) => (
                    <div
                      key={track.languageCode}
                      className="p-4 border rounded-xl bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 flex flex-col justify-between gap-3 shadow-sm hover:border-zinc-300 dark:hover:border-zinc-700 transition-all"
                    >
                      <div className="flex justify-between items-start gap-2">
                        <span className="font-semibold text-sm line-clamp-1">
                          {track.languageName || track.languageCode}
                        </span>
                        <span className="text-xs font-mono text-zinc-500 bg-zinc-100 dark:bg-zinc-800 px-1.5 py-0.5 rounded shrink-0">
                          {track.languageCode}
                        </span>
                      </div>

                      <div className="flex flex-wrap gap-1.5 pt-2 border-t border-zinc-100 dark:border-zinc-800/80">
                        {track.allFormats.map((fmt) => {
                          const key = `${track.languageCode}_${fmt.ext}_auto`;
                          const isDownloading = downloadingKey === key;

                          return (
                            <button
                              key={fmt.ext}
                              onClick={() =>
                                handleDownloadSubtitle(
                                  track.languageCode,
                                  fmt.ext,
                                  true,
                                )
                              }
                              disabled={downloadingKey !== null}
                              className="px-2.5 py-1 text-xs font-mono font-medium rounded-md bg-zinc-100 hover:bg-blue-50 hover:text-blue-600 dark:bg-zinc-800 dark:hover:bg-blue-950/50 dark:hover:text-blue-400 border border-zinc-200 dark:border-zinc-700 transition-colors uppercase cursor-pointer disabled:cursor-not-allowed disabled:opacity-50 flex items-center justify-center min-w-[42px]"
                            >
                              {isDownloading ? (
                                <svg
                                  className="animate-spin h-3.5 w-3.5 text-blue-600 dark:text-blue-400"
                                  xmlns="http://www.w3.org/2000/svg"
                                  fill="none"
                                  viewBox="0 0 24 24"
                                >
                                  <circle
                                    className="opacity-25"
                                    cx="12"
                                    cy="12"
                                    r="10"
                                    stroke="currentColor"
                                    strokeWidth="4"
                                  ></circle>
                                  <path
                                    className="opacity-75"
                                    fill="currentColor"
                                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                                  ></path>
                                </svg>
                              ) : (
                                `.${fmt.ext}`
                              )}
                            </button>
                          );
                        })}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </section>
          </div>
        )}
      </main>
    </div>
  );
}
